# .github/workflows/dev-deploy.yaml
name: Dev Polybot Service Deployment

on:
  push:
    branches:
      - dev

env:
  ...  # Your envs here

jobs:
  Deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app code
        uses: actions/checkout@v2
      - name: SSH to EC2 instance
        run: |
          # TODO your deployment script here...
