name: Dev Polybot Service Deployment

on:
  push:
    branches:
      - dev

env:
  EC2_PUBLIC_IP: 151.20.32.7
  TOKEN: ${{ secrets.DEV_TELGRAM_TOKEN}}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DOMAIN: dev-bot.abdullahfursa.click:8443

jobs:
  Deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the app code
      uses: actions/checkout@v2

    - name: SSH to EC2 instance
      run: |
          echo "$SSH_PRIVATE_KEY" > mykey.pem
          chmod 400 mykey.pem
          ssh -o StrictHostKeyChecking=no -i mykey.pem ubuntu@$EC2_PUBLIC_IP "bash ~/dev_deploy.sh &"
          
