# .github/workflows/prod-deploy.yaml
name: Prod Polybot Service Deployment

on:
  push:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # TODO define this secret in your GitHub repo settings
  TOKEN: ${{ secrets.PROD_TELGRAM_TOKEN}}
  EC2_PUBLIC_IP: 13.53.133.251


jobs:
  Deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app code
        uses: actions/checkout@v2
      - name: SSH to EC2 instance
        run: |
          echo "$SSH_PRIVATE_KEY" > mykey.pem
          chmod 400 mykey.pem
          
          
          ssh -i mykey.pem -o StrictHostKeyChecking=accept-new ubuntu@$EC2_PUBLIC_IP " bash ~/deploy.sh &"
          # TODO your deployment script here...